= Activate AsciiDoc content
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

Previous: Configure website name, title, author and organization

Tutorial 6

This tutorial...

////
sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

// tag::content[]

[.topic.source]
== Enable Asciidoctor gem, set version

[source,ruby]
.+Gemfile+
gem 'asciidoctor', '>= 0.1.4.pre'

[.topic.source]
== Update gems

 $ bundle install

[max-height=305]
.Console output
....
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Using rake (10.1.0) 
Installing asciidoctor (0.1.4.preview.2) 
Using sass (3.2.9) 
Using bootstrap-sass (2.3.2.0) 
Using chunky_png (1.2.8) 
Using fssm (0.2.10) 
Using compass (0.12.2) 
Using compass-960-plugin (0.10.4) 
Using git (1.2.5) 
Using tilt (1.4.1) 
Using haml (4.0.3) 
Installing json (1.8.0) 
Using rb-fsevent (0.9.3) 
Using ffi (1.9.0) 
Using rb-inotify (0.9.0) 
Using rb-kqueue (0.2.0) 
Using listen (1.2.2) 
Using mini_portile (0.5.1) 
Using nokogiri (1.6.0) 
Using rack (1.5.2) 
Using mime-types (1.23) 
Using rest-client (1.6.7) 
Using ruby-s3cmd (0.1.5) 
Using zurb-foundation (4.2.3) 
Using awestruct (0.5.2) 
Using bundler (1.3.5) 
Your bundle is updated!
....

[.topic.source]
== Configure Asciidoctor

[source,yaml]
.+_config/site.yml+
----
# append
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
----

[.topic.source]
== Create a page in AsciiDoc format

[source,asciidoc]
.+about.adoc+
----
= About {sitename} <1>
Your Name
:awestruct-layout: base <2>

{sitename} was founded by {author} during a conference workshop.
It's quickly becoming much bigger than this humble beginning.

This page is written in http://asciidoc.org[AsciiDoc].
It's transformed by http://awestruct.org[Awestruct] and http://asciidoctor.org[Asciidoctor] into a webpage for this static website.
----
<1> Becomes main heading on the page
<2> Specifies the layout to use to frame this content

ifndef::backend-slides[]
NOTE: AsciiDoc does not require a special "front-matter" header.
Instead, regular AsciiDoc attribute entries can be used.
Attribute names that begin with +awestruct-+ are passed to Awestruct as front-matter variables.
endif::backend-slides[]

[.topic.source]
== Add About link to navbar

[source,haml]
.+_layouts/base.html.haml+
----
        %li.divider
          %li
            %a(href="#{site.ctx_path}/about.html") About
----

// TODO also add in footer

[.topic.source]
== Clean and preview site to see changes

 $ rake clean preview

// TODO insert screenshot

// end::content[]

== Next: Configure a theme for AsciiDoc and the website
