= Add Disqus Comments and Google Analytics
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

Previous: Using Images and Videos

Tutorial 12

This tutorial...

////
sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

== Add Disqus comments

=== Add Disqus extension as last entry in +_ext/pipeline.rb+

[source,ruby]
extension Awestruct::Extensions::Disqus.new

=== Edit +_config/site.yml+ to configure Disqus

[source,yaml]
----
disqus: writeadapt-{username}
disqus_generate_id: true
disqus_developer: true
----

// FIXME also add to production profile

=== Edit +_partials/post.html.haml+ to add Disqus comments

[source,haml]
----
  - if !page.listing
    %hr
    - if site.disqus && !site.disqus_developer
      #comments
        =page.post.disqus_comments
----

== Add Google Analytics

=== Edit +_ext/pipeline.rb+

[source,ruby]
helper Awestruct::Extensions::GoogleAnalytics

////
.Edit +_layouts/base.html.haml+
[source,haml]
----
- if site.google_analytics
  =google_analytics_async
----
////

Add analytics key to the configuration:

=== Edit +_config/site.yml+

google_analytics: UA-00000000-1

=== Clean and preview site to see changes

 $ rake clean preview

== Next: Chunked content

