= Awestruct + AsciiDoc Tutorial
Dan Allen
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font

This tutorial...

////
inserting image
inserting video
inserting source code
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
discuss comments
link to tutorial for pushing to github pages
////

== Install Awestruct

.Setup fresh Ruby gemset (Ruby 2.0)
 $ rvm use 2.0.0@writeadapt --create

.Setup fresh Ruby gemset (Ruby 1.9)
 $ rvm use 1.9.3@writeadapt --create

.Install Awestruct
 $ gem install awestruct

.Console output
....
Fetching: tilt-1.4.1.gem (100%)
Successfully installed tilt-1.4.1
Fetching: haml-4.0.3.gem (100%)

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.0.3
Fetching: mini_portile-0.5.1.gem (100%)
Successfully installed mini_portile-0.5.1
Fetching: nokogiri-1.6.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.0
Fetching: sass-3.2.9.gem (100%)
Successfully installed sass-3.2.9
Fetching: chunky_png-1.2.8.gem (100%)
Successfully installed chunky_png-1.2.8
Fetching: fssm-0.2.10.gem (100%)
Successfully installed fssm-0.2.10
Fetching: compass-0.12.2.gem (100%)
Successfully installed compass-0.12.2
Fetching: compass-960-plugin-0.10.4.gem (100%)
Successfully installed compass-960-plugin-0.10.4
Fetching: bootstrap-sass-2.3.2.0.gem (100%)
Successfully installed bootstrap-sass-2.3.2.0
Fetching: zurb-foundation-4.2.3.gem (100%)
Successfully installed zurb-foundation-4.2.3
Fetching: mime-types-1.23.gem (100%)
Successfully installed mime-types-1.23
Fetching: rest-client-1.6.7.gem (100%)
Successfully installed rest-client-1.6.7
Fetching: git-1.2.5.gem (100%)
Successfully installed git-1.2.5
Fetching: ruby-s3cmd-0.1.5.gem (100%)
Successfully installed ruby-s3cmd-0.1.5
Fetching: rb-fsevent-0.9.3.gem (100%)
Successfully installed rb-fsevent-0.9.3
Fetching: ffi-1.9.0.gem (100%)
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.0
Fetching: rb-inotify-0.9.0.gem (100%)
Successfully installed rb-inotify-0.9.0
Fetching: rb-kqueue-0.2.0.gem (100%)
Successfully installed rb-kqueue-0.2.0
Fetching: listen-1.2.2.gem (100%)
Successfully installed listen-1.2.2
Fetching: rack-1.5.2.gem (100%)
Successfully installed rack-1.5.2
Fetching: awestruct-0.5.2.gem (100%)
Successfully installed awestruct-0.5.2
22 gems installed
....

.Check version of Awestruct
 $ awestruct --version

.Console output
....
WARNING: Missing required dependency to activate optional built-in extension minify.rb
  cannot load such file -- htmlcompressor
WARNING: Missing required dependency to activate optional built-in extension coffeescripttransform.rb
  cannot load such file -- coffee-script
Awestruct: 0.5.2
http://awestruct.org/
....

== Create a new Awestruct-based website project

.Make empty directory for website
 $ mkdir writeadapt

.Switch to new directory
 $ cd writeadapt

IMPORTANT: Don't forget to switch to the new directory or else the website will be generated in the wrong place.

.Generate website structure seeded to use Foundation
 $ awestruct -i -f foundation

.Console output
....
WARNING: Missing required dependency to activate optional built-in extension minify.rb
  cannot load such file -- htmlcompressor
WARNING: Missing required dependency to activate optional built-in extension coffeescripttransform.rb
  cannot load such file -- coffee-script
Create directory: /path/to/writeadapt/_config
Create directory: /path/to/writeadapt/_layouts
Create directory: /path/to/writeadapt/_ext
Create file: /path/to/writeadapt/_ext/pipeline.rb
Create file: /path/to/writeadapt/.awestruct_ignore
Create file: /path/to/writeadapt/Rakefile
Create file: /path/to/writeadapt/Gemfile
Create directory: /path/to/writeadapt/stylesheets
directory _site/stylesheets/ 
directory javascripts/foundation/ 
directory javascripts/vendor/ 
   create stylesheets/_normalize.scss 
   create stylesheets/_settings.scss 
   create stylesheets/app.scss 
   create humans.txt 
   create robots.txt 
   create MIT-LICENSE.txt 
   create javascripts/foundation/foundation.orbit.js 
   create javascripts/foundation/foundation.cookie.js 
   create javascripts/foundation/foundation.clearing.js 
   create javascripts/foundation/foundation.magellan.js 
   create javascripts/foundation/foundation.section.js 
   create javascripts/foundation/foundation.alerts.js 
   create javascripts/foundation/foundation.topbar.js 
   create javascripts/foundation/foundation.joyride.js 
   create javascripts/foundation/foundation.interchange.js 
   create javascripts/foundation/foundation.forms.js 
   create javascripts/foundation/foundation.tooltips.js 
   create javascripts/foundation/foundation.dropdown.js 
   create javascripts/foundation/foundation.placeholder.js 
   create javascripts/foundation/foundation.reveal.js 
   create javascripts/vendor/custom.modernizr.js 
   create javascripts/vendor/jquery.js 
   create javascripts/vendor/zepto.js 
   create javascripts/foundation/foundation.js 
   create index.html 
   create _site/stylesheets/app.css 

Now you're awestruct!

To generate and run your site in development mode, execute:

  awestruct -d

or, simply:

  rake

then visit your site at: http://localhost:4242

Create file: /path/to/writeadapt/_config/site.yml
Create file: /path/to/writeadapt/_layouts/base.html.haml
Create file: /path/to/writeadapt/index.html.haml
....

.Website project file tree
....
.
|-- .awestruct/
|   `-- debug.log
|-- .awestruct_ignore
|-- _config/
|   `-- site.yml
|-- _ext/
|   `-- pipeline.rb
|-- Gemfile
|-- humans.txt
|-- index.html.haml
|-- javascripts/
|   |-- foundation/
|   |   |-- foundation.alerts.js
|   |   |-- foundation.clearing.js
|   |   |-- foundation.cookie.js
|   |   |-- foundation.dropdown.js
|   |   |-- foundation.forms.js
|   |   |-- foundation.interchange.js
|   |   |-- foundation.joyride.js
|   |   |-- foundation.js
|   |   |-- foundation.magellan.js
|   |   |-- foundation.orbit.js
|   |   |-- foundation.placeholder.js
|   |   |-- foundation.reveal.js
|   |   |-- foundation.section.js
|   |   |-- foundation.tooltips.js
|   |   `-- foundation.topbar.js
|   `-- vendor/
|       |-- custom.modernizr.js
|       |-- jquery.js
|       `-- zepto.js
|-- _layouts/
|   `-- base.html.haml
|-- Rakefile
|-- robots.txt
|-- _site/
`-- stylesheets/
    |-- app.scss
    |-- _normalize.scss
    `-- _settings.scss
....

.Install Rake and Bundler
 $ gem install rake bundler

.Console output
....
Fetching: rake-10.1.0.gem (100%)
Successfully installed rake-10.1.0
Fetching: bundler-1.3.5.gem (100%)
Successfully installed bundler-1.3.5
2 gems installed
....

.Ensure environment is setup correctly
 $ rake setup

.Generate and preview website
 $ rake

.Console output
....
WARNING: Missing required dependency to activate optional built-in extension minify.rb
  cannot load such file -- htmlcompressor
WARNING: Missing required dependency to activate optional built-in extension coffeescripttransform.rb
  cannot load such file -- coffee-script
Using profile: development
Generating site: http://localhost:4242
[Listen warning]:
The blocking parameter of Listen::Listener#start is deprecated.
Please use Listen::Adapter#start for a non-blocking listener and Listen::Listener#start! for a blocking one.
[2013-01-01 00:00:00] INFO  WEBrick 1.3.1
[2013-01-01 00:00:00] INFO  ruby 2.0.0 (2013-05-14) [x86_64-linux]
[2013-01-01 00:00:00] INFO  WEBrick::HTTPServer#start: pid=10485 port=4242
....

.Preview website
Visit http://localhost:4242 in your web browser.

// TODO insert screenshot

.Halt the preview server
kbd:[Ctrl+C]

.Structure of generated site
....
_site/
|-- humans.txt
|-- index.html
|-- javascripts/
|   |-- foundation/
|   |   |-- foundation.alerts.js
|   |   |-- foundation.clearing.js
|   |   |-- foundation.cookie.js
|   |   |-- foundation.dropdown.js
|   |   |-- foundation.forms.js
|   |   |-- foundation.interchange.js
|   |   |-- foundation.joyride.js
|   |   |-- foundation.js
|   |   |-- foundation.magellan.js
|   |   |-- foundation.orbit.js
|   |   |-- foundation.placeholder.js
|   |   |-- foundation.reveal.js
|   |   |-- foundation.section.js
|   |   |-- foundation.tooltips.js
|   |   `-- foundation.topbar.js
|   `-- vendor/
|       |-- custom.modernizr.js
|       |-- jquery.js
|       `-- zepto.js
|-- robots.txt
`-- stylesheets/
    `-- app.css
....

== Configure website name, title and organization

.Change values in +_config/site.yml+
[source,yaml]
----
name: WriteAdapt
title: WriteAdapt - For People Who Love Content
org: Strategy Media
base_url: ''
haml:
  :ugly: true
----

.Clean and preview site to see changes
 $ rake clean
 $ rake

NOTE: The clean step is required since a change to the configuration file, +_config/site.yml+, does not force pages to be regenerated automatically.

== Activate AsciiDoc content

.Uncomment Asciidoctor gem, +asciidoctor+, in Gemfile
[source,ruby]
gem 'asciidoctor', '>= 0.1.4.pre'

.Update gems
 $ bundle update

.Console output
....
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Using rake (10.1.0) 
Installing asciidoctor (0.1.4.preview.2) 
Using sass (3.2.9) 
Using bootstrap-sass (2.3.2.0) 
Using chunky_png (1.2.8) 
Using fssm (0.2.10) 
Using compass (0.12.2) 
Using compass-960-plugin (0.10.4) 
Using git (1.2.5) 
Using tilt (1.4.1) 
Using haml (4.0.3) 
Installing json (1.8.0) 
Using rb-fsevent (0.9.3) 
Using ffi (1.9.0) 
Using rb-inotify (0.9.0) 
Using rb-kqueue (0.2.0) 
Using listen (1.2.2) 
Using mini_portile (0.5.1) 
Using nokogiri (1.6.0) 
Using rack (1.5.2) 
Using mime-types (1.23) 
Using rest-client (1.6.7) 
Using ruby-s3cmd (0.1.5) 
Using zurb-foundation (4.2.3) 
Using awestruct (0.5.2) 
Using bundler (1.3.5) 
Your bundle is updated!
....

.Create a page in AsciiDoc format
[source,asciidoc]
----
= About WriteAdapt <1>
Your Name
:awestruct-layout: base <2>

WriteAdapt was founded by {author} at a conference workshop.
It's quickly becoming much bigger than these humble beginnings.

This page is written in http://asciidoc.org[AsciiDoc].
It's transformed by http://awestruct.org[Awestruct] and http://asciidoctor.org[Asciidoctor] into a webpage in this static website.
----
<1> Becomes main heading on the page
<2> Specifies the layout to use to frame this content

NOTE: AsciiDoc does not require a special "front-matter" header.
Instead, regular AsciiDoc attribute entries can be used.
Attribute names that begin with +awestruct-+ are passed to Awestruct as front-matter variables.

.Edit +_layouts/base.html.haml+ to add About link to navbar
----
        %li.divider
          %li
            %a{:href=>"#{site.base_url}/about.html"} About
----

// TODO also add in footer

.Preview site to see changes
 $ rake

// TODO insert screenshot

.Add lines to +_config/site.yml+ to configure Asciidoctor
[source,yaml]
----
asciidoctor:
  :safe: safe
  :attributes:
    notitle!: ''
    idprefix: ''
    idseparator: '-'
    icons: font
----

.Clean and preview site to see changes
 $ rake clean preview

== Configure a theme for AsciiDoc and the website

.Switch to the stylesheets directory
 $ cd stylesheets

.Clone the Asciidoctor stylesheet factory repository
 $ git clone --branch embedded-stylesheets https://github.com/asciidoctor/asciidoctor-stylesheet-factory _themes

.Switch back to the project root
 $ cd ..

.Replace content of +stylesheets/app.scss+ to configure theme
[source,scss]
----
@import "_themes/sass/foundation-embedded.scss";
@import "foundation/components/buttons";
@import "foundation/components/top-bar";
@import "foundation/components/inline-lists";

.top-bar a {
  text-decoration: none;
}
----

TIP: Alternative themes include +asciidoctor-embedded+ and +rocket-panda-embedded+.

.Add line at top of +_ext/pipeline.rb+ to load SASS functions for themes
[source,ruby]
require './stylesheets/_themes/lib/functions.rb'

.Remove unnecessary files
 $ rm stylesheets/{_normalize.scss,_settings.scss}

.Edit +_layouts/base.html.haml+ to assign id to main content
[source,haml]
----
  #content.row
    .large-12.columns
      ~ content
----

.Edit +index.html.haml+ to remove horizontal rule under page title
[source,haml]
----
.row
  .large-12.columns
    %h1 Welcome to #{site.name}!
----

////
#{Asciidoctor.render site.name, :doctype => :inline}

%a(href="#{site.base_url}/")=Asciidoctor.render(site.name, :doctype => :inline)
////

.Add lines to +_config/site.yml+ to configure Asciidoctor
[source,yaml]
----
asciidoctor:
  :safe: safe
  :attributes:
    notitle!: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font 
----

.Clean and preview site to see changes
 $ rake clean preview

// TODO insert screenshot (shows larger h1 and lead paragraph)

// TODO show what happens if awestruct-layout is not set

== Activate posts extension (blog, news, etc)

...

== Media formats

=== Source code

.Edit +_config/site.yml+ to configure AsciiDoc source highlighter
[source,yaml]
----
asciidoctor:
  :safe: safe
  :attributes:
    notitle!: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font 
    source-highlighter: coderay
    coderay-css: style
----

.Add CodeRay gem, +coderay+, to +Gemfile+
[source,ruby]
----
gem 'coderay'
----

.Update gems
 $ bundle update

...

=== Images

=== Videos
