= Chunked Content
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

Previous: Add Disqus Comments and Google Analytics

Tutorial 13

This tutorial...

////
sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

// tag::content[]

[.topic.source]
== Define excerpt for post

[source,asciidoc]
----
:excerpt: Excerpt of post.
:awestruct-excerpt: {excerpt}

{excerpt}
----

[.topic.source]
== Use post excerpt

[source,haml]
.Revise +_partials/post.html.haml+
----
  .post-body
    - if page.listing
      %p=page.post.excerpt || summarize(html_to_text(page.post.content), 100)
      %p
        %a.small.secondary.button{:href=>post_url} Read more...
    - else
      =page.post.content
----

// end::content[]

== Post image

// TODO (see Brian's blog)

== Next: Custom Domain Name
