= Configure a theme for AsciiDoc and the website
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

Previous: Activate AsciiDoc content

Tutorial 7

This tutorial...

////
sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

// tag::content[]

[.topic.source]
== Clone Asciidoctor stylesheet factory as a submodule

 $ git submodule add -b embedded-stylesheets \
 https://github.com/asciidoctor/asciidoctor-stylesheet-factory.git \
 stylesheets/_themes

////

[.topic.source]
== Switch to the stylesheets directory

 $ cd stylesheets

[.topic.source]
== Clone the Asciidoctor stylesheet factory repository

 $ git clone --branch embedded-stylesheets https://github.com/asciidoctor/asciidoctor-stylesheet-factory _themes

[.topic.source]
== Switch back to the project root

 $ cd ..
////

[.topic.source]
== Import theme into main stylesheet

. Delete all content in +stylesheets/app.scss+
. Populate the file with the content in the listing below

[source,css]
.+stylesheets/app.scss+
----
$row-width: 72em;
@import "_themes/sass/foundation-embedded.scss";
----

TIP: Alternative themes for the first line include +asciidoctor-embedded+ and +rocket-panda-embedded+.

[.topic.source]
== Add extra styles needed for website layout

[source,css,max-height=335]
.+stylesheets/app.scss+
----
@import "foundation/components/buttons";
@import "foundation/components/button-groups";
@import "foundation/components/top-bar";
@import "foundation/components/inline-lists";
$pagination-link-unavailable-font-color: #e9e9e9;
@import "foundation/components/pagination";

$footer-bg: $body-font-color !default;
$footer-font-color: invert($body-font-color) !default;
.top-bar a {
  text-decoration: none;
}
h1 em {
  letter-spacing: 1px;
}
body > footer {
  background: $footer-bg;
  padding: $panel-padding;
  color: $footer-font-color;
}
----

[.topic.source]
== Load SASS functions for themes

[source,ruby]
.Add line to top of +_ext/pipeline.rb+
require './stylesheets/_themes/lib/functions.rb'

[.topic.source]
== Remove unnecessary files

 $ rm stylesheets/{_normalize.scss,_settings.scss}

IMPORTANT: Also remove the normalize.css link from +_layouts/base.html.haml+.

[.topic.source]
== Assign id to main content

[source,haml]
.Edit +_layouts/base.html.haml+
----
  #content.row
    .large-12.columns
      =content
----

[.topic.source]
== Revise main heading on home page

[source,haml]
.Edit +index.html.haml+
----
.row
  .large-12.columns
    %h1 Welcome to #{Asciidoctor.render site.name, :doctype => :inline}!
----

IMPORTANT: Make sure to remove the +%hr+ under the +%h1+.

[.topic.source]
== Format site name in nav bar

[source,haml]
.Edit +_layouts/base.html.haml+
----
      %li.name
        %h1
          %a(href="#{site.ctx_path}/")
            =Asciidoctor.render(site.name, :doctype => :inline)
----

[.topic.source]
== Clean and preview site to see changes

 $ rake clean preview

// TODO insert screenshot (shows larger h1 and lead paragraph)

// TODO show what happens if awestruct-layout is not set

// end::content[]

== Next: Activate posts extension (blog, news, etc)

