= Deploy website to GitHub Pages
Dan Allen
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

// tag::content[]

[.topic.source]
== Commit and push any outstanding changes

 $ git commit . -m "Enhancements"
 $ git push origin master

[.topic.source]
== Create the publish branch, gh-pages

 $ git checkout --orphan gh-pages
 $ rm -rf *
 $ rm -rf .awestruct* .sass-* .gitignore .gitmodules
 $ git rm --cached *
 $ echo "GitHub Pages placeholder" > index.html
 $ git add index.html .nojekyll
 $ git commit -m "Seed publish branch for GitHub Pages"

// add .ruby-* exclude from this find command
//$ find -maxdepth 1 -not -regex "^\.\(/\.git\)?$" -exec rm -rf {} \;

[.topic.source]
== Push the publish branch

 $ git push origin gh-pages
 $ git checkout master

NOTE: By pushing the *gh-pages* branch, you also activated GitHub Pages to publish your website.

.View your website
----
http://%USERNAME%.github.io/writeadapt-%USERNAME%
----

[.topic.source]
== Setup the Awestruct GitHub Pages deployer

//.Switch to the +master+ branch
// $ git checkout master

[source,yaml]
.Append to +_config/site.yml+
----
profiles:
  development:
    deploy: nil #<1>
  production:
    base_url: http://%USERNAME%.github.io/writeadapt-%USERNAME%
    ctx_path: /writeadapt-%USERNAME%
    asciidoctor:
      :attributes:
        base_url: http://%USERNAME%.github.io/writeadapt-%USERNAME%
        ctx_path: /writeadapt-%USERNAME%
        imagesdir: http://%USERNAME%.github.io/writeadapt-%USERNAME%/images #<2>
    deploy:
      host: github_pages
      branch: gh-pages
----
<1> nil deploy config forces development as default profile
<2> imagesdir must be absolute to work around Atom feed bug

IMPORTANT: Replace `%USERNAME%` with *your* GitHub username.

[.topic.source]
== Commit deployer configuration

 $ git commit _config/site.yml -m "Add profile for GitHub Pages deployment"
 $ git push origin master

[.topic.source]
== Deploy to GitHub Pages

 $ rake clean deploy

////
WARNING: Missing required dependency to activate optional built-in extension minify.rb
  cannot load such file -- htmlcompressor
WARNING: Missing required dependency to activate optional built-in extension coffeescripttransform.rb
  cannot load such file -- coffee-script
Using profile: production
Generating site: http://localhost:4242
Deploying to github_pages
////

.View your website again
----
http://%USERNAME%.github.io/writeadapt-%USERNAME%
----

IMPORTANT: Your Awestruct-based website is now live, and available worldwide!

// FIXME Broken post URLs when running under a context path is a known issue

// end::content[]
