= Install Awestruct
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

// tag::content[]

ifndef::backend-slides[]
In this tutorial, we will:

. Install RVM
. Setup a Ruby gemset
. Install Awestruck
. Check the version of Awestruct via the commandline
endif::backend-slides[]

////
On Mac the Termincal is under utilities

sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

[.topic.source]
== Check Your Ruby version

 $ ruby --version
 # ruby 1.9.3p848 (2013-11-22 revision 40747) [x86_64-linux]

IMPORTANT: You must use the 32-bit version of Ruby 1.9.3 on Windows.

.Windows install steps:
--
. Download Ruby Installer from http://tiny.cc/ruby193win
. Run installer, select default location
. Check "Add Ruby executables to your PATH"
. Configure RubyGems:

  (echo install: --no-rdoc --no-ri) > C:\ProgramData\gemrc
  (echo update: --no-rdoc --no-ri) >> C:\ProgramData\gemrc
--
 
[.topic.source]
== Install RVM

ifndef::backend-slides[If you're using Linux or OSX, open a Terminal window and type the following commands:]

.Linux and OSX
[.no-highlight]
 $ \curl -L https://get.rvm.io -o rvm-installer
 $ bash rvm-installer --ruby=2.0.0

//NOTE: On OSX, you need to first install XCode from the MacApp store or OSX system CD.
 
//ifndef::backend-slides[If you're using Windows, ...]

.Windows
--
Use Ruby as normal. Skip any RVM steps.

TIP: The RVM equivalent for Windows is named https://github.com/vertiginous/pik[pik].
--

////
.Windows (https://github.com/vertiginous/pik[pik])
 > gem install pik
 > pik_install C:\bin
 > pik add C:\ruby\IronRuby-091\bin
 > pik install ruby
////

[.topic.source]
== Create and use a new Ruby gemset (RVM only)

ifndef::backend-slides[On the commandline, type:]

 $ rvm use 2.0.0@writeadapt --create

TIP: If you want to use Ruby 1.9.3, replace +2.0.0+ with +1.9.3+.

[.topic.source]
== Install Awestruct

ifndef::backend-slides[On the commandline, type:]

// $ gem install tilt:1.4.1 awestruct:0.5.4.rc3 asciidoctor
 $ gem install tilt --version 1.4.1
 $ gem install awestruct --version 0.5.4.rc3
 $ gem install asciidoctor

[.incremental]
--
[max-height=262]
.Console output
....
Successfully installed tilt-1.4.1
1 gem installed

HEADS UP! Haml 4.0 has many improvements, but also has changes that may break
your application:

* Support for Ruby 1.8.6 dropped
* Support for Rails 2 dropped
* Sass filter now always outputs <style> tags
* Data attributes are now hyphenated, not underscored
* html2haml utility moved to the html2haml gem
* Textile and Maruku filters moved to the haml-contrib gem

For more info see:

http://rubydoc.info/github/haml/haml/file/CHANGELOG.md

Successfully installed haml-4.0.4
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.5.10
Successfully installed rb-fsevent-0.9.3
Building native extensions.  This could take a while...
Successfully installed ffi-1.9.3
Successfully installed rb-inotify-0.9.2
Successfully installed rb-kqueue-0.2.0
Successfully installed listen-1.1.6
Successfully installed sass-3.3.0.rc.2
Successfully installed multi_json-1.8.2
Successfully installed compass-core-1.0.0.alpha.13
Successfully installed chunky_png-1.2.9
    Compass is charityware. If you love it, please donate on our behalf at http://umdf.org/compass Thanks!
Successfully installed compass-1.0.0.alpha.13
Successfully installed compass-960-plugin-0.10.4
Successfully installed bootstrap-sass-3.0.2.1
Successfully installed zurb-foundation-4.3.2
Successfully installed mime-types-1.25
Successfully installed rest-client-1.6.7
Successfully installed ruby-s3cmd-0.1.5
Successfully installed rack-1.5.2
Successfully installed awestruct-0.5.4.rc3
20 gems installed

Successfully installed asciidoctor-0.1.4
1 gem installed
....
--

[.topic.source]
== Check version of Awestruct

ifndef::backend-slides[On the commandline, type:]

 $ awestruct --version

[.incremental]
--
.Console output
....
Awestruct: 0.5.4.rc3
http://awestruct.org/
....
--

// end::content[]

== Next: Setup a new website project with Awestruct

