= Use git to take a snapshot of initial state
Dan Allen; Sarah White
:experimental:
:toc2:
:sectanchors:
:idprefix:
:idseparator: -
:icons: font
:source-highlighter: coderay

Previous: Install Rake and Bundler

Tutorial 4

This tutorial...

////
sidebar in layout (and other layouts like on reuze.me)
inserting gist
sentence per line
post excerpt and other types of "chunks" (chunked content)
link to tutorial for pushing to github pages
styles for posts listing page (headings too big)
tip about not loading certain extensions when profile is development
slides
favicon
git history at bottom of file
docinfo or common include
timezone handling
author bio at bottom of post (see smashingmagazine or alistapart for example)
////

// tag::content[]

[.topic.source]
== Initialize new git repository

 $ git init .

[.incremental]
--
.Console output
....
Initialized empty Git repository in ...
....
--

[.topic.source]
== Instruct git to ignore generated files
 
 $ cat > .gitignore << LINES
 /.awestruct/
 /.ruby-*
 /.sass-cache/
 /_site/
 /_tmp/
 /Gemfile.lock
 LINES

[.incremental]
--
ifndef::backend-slides[After running this command, the the +.gitignore+ file should have the following content:]

.Contents of +.gitignore+
....
/.awestruct/
/.ruby-*/
/.sass-cache/
/_site/
/_tmp/
/Gemfile.lock
....
--

[.topic.source]
== Disable Jekyll

 $ touch .nojekyll

[.topic.source]
== Add all non-ignored files to the git repository

 $ git add .

[.topic.source]
== Commit the changes to make the snapshot

 $ git commit -m 'Initial import of website sources'

.Console output
....
 30 files changed, 18757 insertions(+)
 create mode 100644 .awestruct_ignore
 create mode 100644 .gitignore
 create mode 100644 .nojekyll
 create mode 100644 Gemfile
 create mode 100644 Rakefile
 create mode 100644 _config/site.yml
 create mode 100644 _ext/pipeline.rb
 create mode 100644 _layouts/base.html.haml
 create mode 100644 humans.txt
 create mode 100644 index.html.haml
 create mode 100644 javascripts/foundation/foundation.alerts.js
 create mode 100644 javascripts/foundation/...
 create mode 100644 javascripts/vendor/custom.modernizr.js
 create mode 100644 javascripts/vendor/jquery.js
 create mode 100644 javascripts/vendor/zepto.js
 create mode 100644 robots.txt
 create mode 100644 stylesheets/_normalize.scss
 create mode 100644 stylesheets/_settings.scss
 create mode 100644 stylesheets/app.scss
....

TIP: Changes are now tracked by git.
You can rollback at any time.

[.topic]
== Create repository on GitHub

Owner:: $${username}$$
Repository name:: writeadapt-$${username}$$
Description (optional):: An Awestruct demo site
More info::
See https://help.github.com/articles/create-a-repo#make-a-new-repository-on-github[Make a new repository on GitHub]

[.topic.source]
== Connect git repository to GitHub remote

 $ git remote add origin https://github.com/{username}/writeadapt-{username}
 $ git push origin master

IMPORTANT: Replace `{username}` with your GitHub username.

// end::content[]

== Next: Configure website name, title, author and organization
